@api = http://localhost:4000/api/auth

###
POST {{api}}/sign-up
Content-Type: application/json

{
    "username": "Chicha",
    "email": "chicha@gmail.com",
    "password": "claudiochicha78"
}
###
POST {{api}}/sign-in
Content-Type: application/json

{
    "email": "chicha@gmail.com",
    "password": "claudiochicha78"
}