@api = http://localhost:4000/api/roles

###
POST {{api}}
Content-Type: application/json

{
    "name": "user"
}
###
GET {{api}}
###
DELETE {{api}}/11
###
PUT {{api}}/15
Content-Type: application/json

{
    "name": "User"
}