CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL,
    updatedAt TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS videogames (
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE,
    image VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL,
    updatedAt TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    id SERIAL PRIMARY KEY,
    comment VARCHAR(290) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL, 
    updatedAt TIMESTAMP WITH TIME ZONE NOT NULL,
    userId INTEGER REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    videogamesId INTEGER REFERENCES videogames (id) ON DELETE CASCADE ON UPDATE CASCADE
);
